#!/bin/sh

# This is to find the containing directory
self=$0
containingdir=${self%/*}

# Set the appropriate owner, group and permissions
# Also, remove the .DS_Store
cd $containingdir/package_contents/
sudo chown -v -R root:admin *
sudo chmod -v -R ug=rwX,o=r-X *

# This is where the packagemaker binary is on my computer,
# depending on where it is on yours you may have to change
# the following line:
cd /Developer/usr/bin

# These are the commands to packagemaker (-build is a backwards-compatibility
# operation as packagemaker 3 uses flat packages supported only
# by Mac OS 10.5
./packagemaker -build -v -ds -p $containingdir/pygraphics_installer.pkg \
-i $containingdir/Info.plist \
-f $containingdir/package_contents \
-d $containingdir/resources/Description.plist \
-r $containingdir/resources