"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

__docformat__ = 'restructuredtext'
__version__ = '$Id: setup.py 1855 2008-03-01 11:29:25Z Paul Gries $'

VERSION='2.1'

LONG_DESC='''PyMedia provides a set of easy-to-use procedural media
manipulation tools and is intended for new programmers.  It is based on a
Jython library developed by Mark Guzdial at Georgia Tech.'''

AUTHOR='Jen Campbell, Paul Gries, Leo Kaliazine, Chris Maddison, Hardeep Singh, Jason Montojo, Sarah Nason'

APP = ['__init__.py']
DATA_FILES = ['color.py',
 'media.py',
 'mediawindows.py',
 'old-setup.py',
 'picture.py',
 'pixel.py',
 'sample.py',
 'setup.py',
 'sound.py']
OPTIONS = {'argv_emulation': True}

CLASSIFIERS=[
    #'Development Status :: 5 - Production/Stable',
    'Environment :: MacOS X',
    'Environment :: Win32 (MS Windows)',
    'Environment :: X11 Applications',
    'Intended Audience :: New programmers',
    #'License :: OSI Approved :: BSD License',
    'Operating System :: MacOS :: MacOS X',
    'Operating System :: Microsoft :: Windows', # XP
    'Operating System :: POSIX :: Linux',
    'Programming Language :: Python',
    #'Topic :: Games/Entertainment',
    'Topic :: Software Development :: Libraries :: Python Modules',
    ]


setup(
    name='PyMedia',
    app=APP,
    license='GPL',
    version=VERSION,
    url='http://code.google.com/p/pygraphics',
    author=AUTHOR,
    author_email='pgries@cs.toronto.edu',
    classifiers=CLASSIFIERS,
    description='Easily-accessible library for media manipulation',
    extra_path = "pygraphics",
    long_description=LONG_DESC,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
